[package]
name = "sealedinfra"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.14", features = ["derive", "unstable-doc"] }
config = "0.14.0"
env_logger = "0.11.5"
flexi_logger = "0.28.5"
k8s-openapi = "0.22.0"
kube = { version = "0.93", features = ["runtime", "derive"] }
log = { version = "0.4.22", features = ["serde"] }
serde = { version = "1.0.205", features = ["derive"] }
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
tracing = { version = "0.1.40", features = ["log"] }

[dev-dependencies]
k8s-openapi = { version = "0.22.0", features = ["v1_30"] }

[build-dependencies]
vergen-gitcl = { version = "1", features = ["build", "cargo", "rustc"] }
anyhow = "1.0.86"
