working_directory: /tmp/fp
ssh_key: ~/.ssh/herring_id_ed25519
docker_config:
  repository: git@bitbucket.org:financialpayments/tupay.git
  branch: origin/eol/upgrade
docker:
  builder:
    builder_name: "bob"
    dockerfile: .devcontainer/Dockerfile
    tags: 
      - latest